import type { Metadata } from "next";
import localFont from "next/font/local";
import "swiper/css";
import "./globals.css";

const guminert = localFont({
  src: [
    {
      path: "../public/fonts/guminert/Guminert.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/guminert/Guminert-Medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "../public/fonts/guminert/Guminert-SemiBold.woff2",
      weight: "600",
      style: "normal",
    },
    {
      path: "../public/fonts/guminert/Guminert-ExtraBold.woff2",
      weight: "800",
      style: "normal",
    },
  ],
  variable: "--font-guminert",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={`${guminert.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col font-sans">
        {children}

        <div className="fixed bottom-0 left-0 right-0 z-999 h-50 flex-none pointer-events-none overflow-visible backdrop-blur-md [mask:linear-gradient(180deg,rgba(0,0,0,0)_0%,black_100%)]"></div>
      </body>
    </html>
  );
}
