import { Chatbot } from "@/components/Chatbot";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "swiper/css";
import "./globals.css";

const guminert = localFont({
  src: [
    {
      path: "../public/fonts/guminert/Guminert.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/guminert/Guminert-Medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "../public/fonts/guminert/Guminert-SemiBold.woff2",
      weight: "600",
      style: "normal",
    },
    {
      path: "../public/fonts/guminert/Guminert-ExtraBold.woff2",
      weight: "800",
      style: "normal",
    },
  ],
  variable: "--font-guminert",
  display: "swap",
});
const qurova = localFont({
  src: [
    {
      path: "../public/fonts/qurova/QurovaDEMO-Light.woff2",
      weight: "300",
      style: "normal",
    },
    {
      path: "../public/fonts/qurova/QurovaDEMO-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/qurova/QurovaDEMO-Medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "../public/fonts/qurova/QurovaDEMO-SemiBold.woff2",
      weight: "600",
      style: "normal",
    },
    {
      path: "../public/fonts/qurova/QurovaDEMO-Bold.woff2",
      weight: "800",
      style: "normal",
    },
  ],
  variable: "--font-qurova",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Vorklye Shopify Agency & Digital Commerce Experts",
  description: "Generated by Vorklye",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={`${guminert.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col font-sans">
        {children}
        <Chatbot />
      </body>
    </html>
  );
}
